### PR TITLE
add quotes to satisfy sf 3.1 yaml deprecations

### PR DESCRIPTION
**Pull request by ckifer**
Container parameters enclosed with "%" need to be enclosed in quotes

### CODE REVIEW

**Comment by tchapi** [comment]
Hello @comur ! Can you accept this PR ? It's only deprecation warnings so it's pretty safe I guess — thanks !

**Comment by Zoopme** [comment]
Hi,
Also included in pull request #117 for Symfony 4

**Comment by tchapi** [comment]
It looks like this project is not maintained anymore :/ ... any forks that are active ?

**Comment by Zoopme** [comment]
No idea but the project has worked for me so far, and has been more helpful than the alternatives I found. I am using my own fork on Symfony 4 and crossing fingers that @comur is still active to validate my pull request :) @comur, what do you say ? Thanks in advance for your input.

**Comment by ckifer** [comment]
@Zoopme yeah I agree with tchpai. There hasn't been any activity here for almost a year. At this point, your fork looks like it is the furthest ahead. I'm not using Symfony any more, but good luck!

**Comment by comur** [comment]
Hi
Sorry I just saw your PR and comments, I merge it, thanks and sorry for late answer

**Pull request merged**
