### PR TITLE
[update] Compatibility with Symfony3

### PR DESCRIPTION
**Pull request by anthonyherve**

### CODE REVIEW

**Comment by petegore** [comment]
Nice work, buddy !

**Careful **: this PR will probably kill the Symfony2 compatibility.
You need to create a specific branch to merge it which will be pull by Sf3 users only.

**Comment by anthonyherve** [comment]
I added some commits after testing.

**Comment by comur** [comment]
I created a new branch 1.3, can you send your PR on that so master can stay compatible with SF2 for now. Can you also add a comment on README to tell people to download 1.3 for SF3 compatibility and master for SF2 compatibility pls ?

Thanks !

**Comment by anthonyherve** [comment]
I close this PR because I created a new one for branch 1.3

**Pull request closed without merging**
